### ISSUE TITLE
国服日历无法获取

### ISSUE THREAD

**Issue by yuuki-nya** [zyujs/pcr_calendar#12]
刚刚clone的最新版
Hoshino控制台报：解析B站日程表失败
台服，日服正常

**Comment by Sasa-kid** [comment]
我也是这个情况，翻了下，应该是event.py里的 https://mahomaho-insight.info/cached/gameevents.json 访问不了，所以解析失败了

**Comment by lolikyo** [comment]
![5811d2a6d3f585a5cc88e6a20f38e13](https://user-images.githubusercontent.com/49865203/165911682-d50a65d0-73ed-4381-9903-c85cc6c398be.png)
4月15日之后解析出错
