### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by yoooowi** [zyujs/pcr_calendar#3]
`event`的`get_pcr_now`函数里面用的`datetime.datetime.now()`这个函数，返回的是服务器的本地时间，如果服务器时间不是UTC+8的话就有可能出问题。能否加上时区信息`pytz.timezone('Asia/Shanghai')`作为参数？（需要 import `pytz` 这个包）

**Comment by zyujs** [comment]
这个包坑更多, 建议自己改服务器时区.
