### ISSUE TITLE
CN日历数据源貌似没更新了

### ISSUE THREAD

**Issue by NepPure** [zyujs/pcr_calendar#6]
https://mahomaho-insight.info/cached/gameevents.json

不知道还有无什么其他合适的

**Comment by NepPure** [comment]
https://github.com/NepPure/pcr_calendar

直接换了官网的日历，因为fork改成原神了 不好合并

**Comment by zyujs** [comment]
已更新

**Comment by NepPure** [comment]
还是看大佬的py清爽 学废了！ o(╥﹏╥)o
